name: Purge Cache

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  ENDPOINT: '-X DELETE "https://api.cloudflare.com/client/v4/zones/629e8bfaf0bb8becf800b692bb4a5443/purge_cache"'
  EMAIL: '-H "X-Auth-Email: ${{ SECRETS.EMAIL }}"'
  CURL_AUTH: '-H "Authorization: Bearer ${{ SECRETS.PURGE_CACHE }}"'
  CURL_CONTENT: '-H "Content-Type: application/json"'
  CURL_DATA: --data '{"purge_everything":true}'
  
jobs:
  purge:
    name: purge cache
    runs-on: ubuntu-latest
    
    steps:
    
    - name: purge cache
      run: |
        curl ${{ env.ENDPOINT }} ${{ env.email }} ${{ env.CURL_AUTH }} ${{ env.CURL_CONTENT }} ${{ env.CURL_DATA }}
    
