
name: Prod Release

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - name: Log Details
        run: npm version

      - name: Install dependencies
        run: npm install

      - name: Install gatsby
        run: npm install -g gatsby-cli

      - name: Build Gatsby
        run: gatsby build
    
      - name: Install Wrangler
        run: npm i @cloudflare/wrangler -g

      - name: config wrangler
        run: CF_API_TOKEN=${{ secrets.CF_API_TOKEN }} wrangler publish
