
name: Prod Release

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 19.4.0

      - name: Install dependencies
        run: npm install
        
      - name: NPM run clean
        run: npm run clean

      - name: Install yarn
        run: npm install -g yarn
      
      - name: Yarn
        run: yarn install --frozen-lockfile

      - name: Install gatsby
        run: npm install -g gatsby-cli

      - name: Build Gatsby
        run: gatsby build
      
      - name: Install Wrangler
        run: npm i @cloudflare/wrangler -g

      - name: config wrangler
        run: CF_API_TOKEN=${{ secrets.CF_API_TOKEN }} wrangler publish
